### ISSUE TITLE
Can't install libncsnd

### ISSUE THREAD

**Issue by AAM1075** [PabloMK7/libncsnd#1]
Hello, I've got a problem when I try to install this. I get this error: `fatal error: ncsnd.h: No such file or directory`. Do you know what might've caused this?

**Comment by PabloMK7** [comment]
Make sure you followed the installation instructions properly. That error is because the library is not properly installed or you didn't add the dependencies to the makefile.

**Comment by AAM1075** [comment]
I didn't follow the instructions (I forgot to add the lines to the makefile). Sorry lol
